-- Seed du référentiel Pays (codes ISO 3166-1 alpha-2)
INSERT INTO public.country (name, iso_code, is_active, created_at, updated_at) VALUES
    ('Allemagne',            'DE', true, NOW(), NOW()),
    ('Argentine',            'AR', true, NOW(), NOW()),
    ('Autriche',             'AT', true, NOW(), NOW()),
    ('Canada',               'CA', true, NOW(), NOW()),
    ('Congo',                'CG', true, NOW(), NOW()),
    ('Egypte',               'EG', true, NOW(), NOW()),
    ('États-Unis',           'US', true, NOW(), NOW()),
    ('France',               'FR', true, NOW(), NOW()),
    ('Hongrie',              'HU', true, NOW(), NOW()),
    ('Israel',               'IL', true, NOW(), NOW()),
    ('Japon',                'JP', true, NOW(), NOW()),
    ('Mexique',              'MX', true, NOW(), NOW()),
    ('Portugal',             'PT', true, NOW(), NOW()),
    ('Royaume Uni',          'GB', true, NOW(), NOW()),
    ('Suède',                'SE', true, NOW(), NOW()),
    ('Tunisie',              'TN', true, NOW(), NOW()),
    ('Afrique du Sud',       'ZA', true, NOW(), NOW()),
    ('Australie',            'AU', true, NOW(), NOW()),
    ('Brésil',               'BR', true, NOW(), NOW()),
    ('Chine',                'CN', true, NOW(), NOW()),
    ('Danemark',             'DK', true, NOW(), NOW()),
    ('Émirats arabes unis',  'AE', true, NOW(), NOW()),
    ('Espagne',              'ES', true, NOW(), NOW()),
    ('Gabon',                'GA', true, NOW(), NOW()),
    ('Inde',                 'IN', true, NOW(), NOW()),
    ('Italie',               'IT', true, NOW(), NOW()),
    ('Maroc',                'MA', true, NOW(), NOW()),
    ('Pologne',              'PL', true, NOW(), NOW()),
    ('Roumanie',             'RO', true, NOW(), NOW()),
    ('Slovaquie',            'SK', true, NOW(), NOW()),
    ('Suisse',               'CH', true, NOW(), NOW()),
    ('Turquie',              'TR', true, NOW(), NOW())
ON CONFLICT (name) DO NOTHING;
