-- Seed du référentiel Pays (codes ISO 3166-1 alpha-2)
INSERT INTO public.country (name, iso_code, is_active) VALUES
    ('Allemagne',            'DE', true),
    ('Argentine',            'AR', true),
    ('Autriche',             'AT', true),
    ('Canada',               'CA', true),
    ('Congo',                'CG', true),
    ('Egypte',               'EG', true),
    ('États-Unis',           'US', true),
    ('France',               'FR', true),
    ('Hongrie',              'HU', true),
    ('Israel',               'IL', true),
    ('Japon',                'JP', true),
    ('Mexique',              'MX', true),
    ('Portugal',             'PT', true),
    ('Royaume Uni',          'GB', true),
    ('Suède',                'SE', true),
    ('Tunisie',              'TN', true),
    ('Afrique du Sud',       'ZA', true),
    ('Australie',            'AU', true),
    ('Brésil',               'BR', true),
    ('Chine',                'CN', true),
    ('Danemark',             'DK', true),
    ('Émirats arabes unis',  'AE', true),
    ('Espagne',              'ES', true),
    ('Gabon',                'GA', true),
    ('Inde',                 'IN', true),
    ('Italie',               'IT', true),
    ('Maroc',                'MA', true),
    ('Pologne',              'PL', true),
    ('Roumanie',             'RO', true),
    ('Slovaquie',            'SK', true),
    ('Suisse',               'CH', true),
    ('Turquie',              'TR', true)
ON CONFLICT (name) DO NOTHING;
